[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bet = "6fYXqWh7p9drrq1j9JSRsi7WnU4i6mC57jNm9R5Xmkck"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
